### PR TITLE
Support for --use

### PR DESCRIPTION
**Pull request by rowanoulton**
Hey,

I've put together a fork to support the `--use` argument, in the same way that [postcss-cli](https://github.com/postcss/postcss-cli) does. It's purely selfish in that I'm used to the postcss-cli approach and wanted to emulate it here with your excellent module.

I don't know if this is something you'd be interested in merging and I certainly understand if it's not a direction you'd like to take but I wanted to share it with you incase it's useful anyway.  If you _are_ keen,  I could look to extend it to support both styles of config and avoid any breaking changes for existing users.

Let me know what you think, and cheers for the super useful project :v:

### CODE REVIEW

**Comment by GitScrum** [comment]
Hey !

I would like to leave the current functionality and add your wonderful idea. 

I can realize for you this option in the near future or Pripyat your pull request which will retain the current functionality. 

Thank you for your interest in the project. :+1:

**Comment by GitScrum** [comment]
@rowanoulton I added yours wonderful idea. Now you need to update the package and use --use.
Close this PR ?

**Comment by rowanoulton** [comment]
@GitScrum Awesome, appreciate you bundling it in. 

Does it support plugin options passed in as arguments? An example [here](https://github.com/GitScrum/posthtml-cli/pull/71/files#diff-2cce40143051e25f811b56c79d619bf5R60) which permits you do to something like:

```console
posthtml -u posthtml-custom-elements --posthtml-custom-elements.defaultTag "span"
```

**Comment by GitScrum** [comment]
@rowanoulton Yep, i added example in readme.

**Comment by GitScrum** [comment]
Yep, supports similarly postcss-cli [--use](https://github.com/code42day/postcss-cli#--use-u) and [example](https://github.com/code42day/postcss-cli#examples).
[posthtml-cli example use](https://github.com/GitScrum/posthtml-cli#options-use)

**Comment by rowanoulton** [comment]
@GitScrum hey, apologies for the slow response.

Awesome, thanks for rolling it in!

There is one case that I've noticed isn't supported: config supplied in string format. Example:

```console
posthtml --use posthtml-css-modules --posthtml-css-modules "path/to/styles.css.json" --output dist/index.html --input src/index.html
```

**Comment by GitScrum** [comment]
Thank you for showing interest in my pack and bug report. I created a [task](https://github.com/GitScrum/posthtml-cli/issues/82) on the solution of this problem.

**Pull request closed without merging**
